name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Run script
        env:
          OKX_API_KEY: ${{ secrets.OKX_API_KEY }}
          OKX_API_SECRET: ${{ secrets.OKX_API_SECRET }}
          OKX_API_PASSPHRASE: ${{ secrets.OKX_API_PASSPHRASE }}
        run: deno run --allow-net --allow-read main.ts

